version: '3'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: anidra
      MYSQL_DATABASE: anidra
      MYSQL_USER: anidra
      MYSQL_PASSWORD: anidra
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  flyway:
    image: flyway/flyway:11-alpine
    volumes:
      - ./sql_versions:/flyway/sql
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - FLYWAY_URL=jdbc:mysql://mysql:3306/anidra?allowPublicKeyRetrieval=true&useSSL=false
      - FLYWAY_USER=anidra
      - FLYWAY_PASSWORD=anidra
      - FLYWAY_VALIDATE_MIGRATION_NAMING=true
    command: baseline migrate
    #command: -url=jdbc:mysql://mysql:3306/anidra -schemas=anidra -user=root -password=anidra migrate
