-- CREATE DATABASE IF NOT EXISTS `anidra` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `anidra`;

-- ALTER USER 'your_username'@'localhost' IDENTIFIED WITH caching_sha2_password BY 'your_password';

CREATE TABLE IF NOT EXISTS `anidra`.`Doctor_Hospital` (
  `Doctor_Hospital_Index` VARCHAR(20) NOT NULL,
  `DOCTOR_KEY` VARCHAR(20) NOT NULL,
  `HOSPITAL_KEY` VARCHAR(20) NOT NULL,
  `DOCTOR_ID` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Doctor_Hospital_Index`),
  INDEX `DOCTOR_KEY` (`DOCTOR_KEY` ASC, `HOSPITAL_KEY` ASC) VISIBLE,
  INDEX `HOSPITAL_KEY` (`HOSPITAL_KEY` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE TABLE IF NOT EXISTS `anidra`.`PM_ML` (
  `SENSOR_ID` VARCHAR(20) NULL DEFAULT NULL,
  `SENSOR_ALLOC_ID` VARCHAR(20) NULL DEFAULT NULL,
  `ALARM_REASONS` VARCHAR(200) NULL DEFAULT NULL,
  `SPO2_VAL` DECIMAL(10,0) NULL DEFAULT NULL,
  `PR_VAL` DECIMAL(10,0) NULL DEFAULT NULL,
  `TEMP_VAL` DECIMAL(10,0) NULL DEFAULT NULL,
  `RESP_VAL` DECIMAL(10,0) NULL DEFAULT NULL,
  `SYS_VAL` DECIMAL(10,0) NULL DEFAULT NULL,
  `DIA_VAL` DECIMAL(10,0) NULL DEFAULT NULL,
  `CREATE_TIMESTAMP` TIMESTAMP NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE TABLE IF NOT EXISTS `anidra`.`Prescription` (
  `prescription_id` INT NOT NULL AUTO_INCREMENT,
  `patient_key` VARCHAR(20) NOT NULL,
  `prescription_date` DATE NOT NULL,
  `prescription_text` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`prescription_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;

CREATE TABLE IF NOT EXISTS `anidra`.`admin` (
  `Admin_Key` VARCHAR(20) NOT NULL,
  `First_Name` VARCHAR(25) NOT NULL,
  `Last_Name` VARCHAR(25) NOT NULL,
  `Phone_Primary` VARCHAR(20) NOT NULL,
  `Phone_Secondary` VARCHAR(20) NULL DEFAULT NULL,
  `Email_Id` VARCHAR(30) NOT NULL,
  `Job_Title` VARCHAR(30) NULL DEFAULT NULL,
  `User_Key` VARCHAR(20) NOT NULL,
  `CREATE_TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFY_TIMESTAMP` TIMESTAMP NULL DEFAULT NULL,
  `CREATE_USERID` VARCHAR(20) NOT NULL,
  `MODIFY_USERID` VARCHAR(20) NOT NULL,
  `Admin_ID` VARCHAR(30) NULL DEFAULT NULL,
  `TITLE` VARCHAR(20) NOT NULL,
  `HOSPITAL_KEY` VARCHAR(20) NOT NULL,
  `Status` VARCHAR(1) NOT NULL DEFAULT 'Y',
  PRIMARY KEY (`Admin_Key`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;

CREATE TABLE IF NOT EXISTS `anidra`.`alert_log` (
  `alert_Id` VARCHAR(20) NOT NULL,
  `type` VARCHAR(15) NOT NULL,
  `message` VARCHAR(256) NOT NULL,
  `create_timestamp` VARCHAR(30) NOT NULL,
  `MEWS_KEY` VARCHAR(20) NULL DEFAULT NULL,
  `patient_Key` VARCHAR(20) NOT NULL,
  `hospital_key` VARCHAR(20) NULL DEFAULT NULL,
  `status` VARCHAR(10) NOT NULL DEFAULT 'new',
  `action` VARCHAR(100) NULL DEFAULT NULL,
  `action_time` VARCHAR(25) NULL DEFAULT NULL,
  `rating` INT NULL DEFAULT '0',
  `ecg_window_key` BINARY(16) NULL DEFAULT NULL,
  PRIMARY KEY (`alert_Id`),
  INDEX `fk_hospitalKey` (`hospital_key` ASC) VISIBLE,
  INDEX `patient_Key` USING BTREE (`patient_Key`) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE TABLE IF NOT EXISTS `anidra`.`algorithm` (
  `ALGO_ID` VARCHAR(20) NOT NULL,
  `ALGO_NAME` VARCHAR(50) NOT NULL,
  `ALGO_DESC` VARCHAR(250) NULL DEFAULT NULL,
  `Status` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`ALGO_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE TABLE IF NOT EXISTS `anidra`.`algo_subscription` (
  `SUBSCRIPTION_ID` VARCHAR(20) NOT NULL,
  `ALGO_ID` VARCHAR(20) NOT NULL,
  `HOSPITAL_KEY` VARCHAR(20) NOT NULL,
  `STATUS` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`SUBSCRIPTION_ID`),
  INDEX `FK_ALGO_ID` (`ALGO_ID` ASC) VISIBLE,
  INDEX `FK_hospitalkey` (`HOSPITAL_KEY` ASC) VISIBLE,
  CONSTRAINT `algo_subscription_ibfk_1`
    FOREIGN KEY (`ALGO_ID`)
    REFERENCES `anidra`.`algorithm` (`ALGO_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE TABLE IF NOT EXISTS `anidra`.`algo_monitor_patient` (
  `MONITOR_ID` VARCHAR(20) NOT NULL,
  `SUBSCRIPTION_ID` VARCHAR(20) NOT NULL,
  `PATIENT_KEY` VARCHAR(20) NOT NULL,
  `STATUS` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`MONITOR_ID`),
  INDEX `FK_SubId` (`SUBSCRIPTION_ID` ASC) VISIBLE,
  INDEX `FK_PatientKey` (`PATIENT_KEY` ASC) VISIBLE,
  CONSTRAINT `algo_monitor_patient_ibfk_1`
    FOREIGN KEY (`SUBSCRIPTION_ID`)
    REFERENCES `anidra`.`algo_subscription` (`SUBSCRIPTION_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE TABLE IF NOT EXISTS `anidra`.`sensor` (
  `sensor_id` VARCHAR(20) NOT NULL,
  `sensor_MAC` VARCHAR(18) NOT NULL,
  `tablet_MAC` VARCHAR(50) NULL DEFAULT NULL,
  `sensor_name` VARCHAR(250) NOT NULL,
  `tablet_name` VARCHAR(250) NOT NULL,
  `hospital_key` VARCHAR(20) NULL DEFAULT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT '1',
  `API_ACCESS_KEY` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`sensor_id`),
  INDEX `FK_hospitalkey` (`hospital_key` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE TABLE IF NOT EXISTS `anidra`.`api` (
  `user_key` VARCHAR(20) NOT NULL,
  `sensor_id` VARCHAR(20) NOT NULL,
  `api_key` VARCHAR(20) NOT NULL,
  `expire` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`user_key`, `sensor_id`),
  UNIQUE INDEX `user_key` USING BTREE (`user_key`, `sensor_id`) VISIBLE,
  INDEX `fk_sensorID` (`sensor_id` ASC) VISIBLE,
  CONSTRAINT `fk_sensorID`
    FOREIGN KEY (`sensor_id`)
    REFERENCES `anidra`.`sensor` (`sensor_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE TABLE IF NOT EXISTS `anidra`.`cs_additional_info` (
  `ADDITIONAL_INFO_KEY` VARCHAR(25) NOT NULL,
  `PARENT_TABLE` VARCHAR(50) NOT NULL,
  `PARENT_KEY` VARCHAR(25) NOT NULL,
  `NAME` VARCHAR(40) NOT NULL,
  `INFO_GROUP` VARCHAR(50) NOT NULL,
  `CHAR_VALUE` VARCHAR(4000) NOT NULL,
  `INTEGER_VALUE` DECIMAL(20,0) NOT NULL,
  `DOUBLE_VALUE` DECIMAL(14,4) NOT NULL,
  `CREATE_TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFY_TIMESTAMP` DATETIME NOT NULL,
  `CREATE_USERID` VARCHAR(50) NOT NULL,
  `MODIFY_USERID` VARCHAR(50) NOT NULL,
  `CREATE_APPLICATION` VARCHAR(50) NOT NULL,
  `MODIFY_APPLICATION` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ADDITIONAL_INFO_KEY`),
  UNIQUE INDEX `PARENT_TABLE_2` (`PARENT_TABLE` ASC, `PARENT_KEY` ASC, `NAME` ASC) VISIBLE,
  INDEX `PARENT_TABLE` (`PARENT_TABLE` ASC) VISIBLE,
  INDEX `PARENT_KEY` (`PARENT_KEY` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE TABLE IF NOT EXISTS `anidra`.`db_calender` (
  `c_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE TABLE IF NOT EXISTS `anidra`.`default_patient_threshold` (
  `THRESHOLD_TYPE` VARCHAR(20) NOT NULL,
  `SPO2_MAX` DECIMAL(3,0) NOT NULL,
  `SPO2_MIN` DECIMAL(3,0) NOT NULL,
  `RESP_RATE_MAX` DECIMAL(3,0) NOT NULL,
  `RESP_RATE_MIN` DECIMAL(3,0) NOT NULL,
  `PULSE_RATE_MAX` DECIMAL(3,0) NOT NULL,
  `PULSE_RATE_MIN` DECIMAL(3,0) NOT NULL,
  `TEMPERATURE_MAX` DECIMAL(3,1) NOT NULL,
  `TEMPERATURE_MIN` DECIMAL(3,1) NOT NULL,
  `SYS_PRESSURE_MAX` DECIMAL(3,0) NOT NULL,
  `SYS_PRESSURE_MIN` DECIMAL(3,0) NOT NULL,
  `DIA_PRESSURE_MAX` DECIMAL(3,0) NOT NULL,
  `DIA_PRESSURE_MIN` DECIMAL(3,0) NOT NULL,
  PRIMARY KEY (`THRESHOLD_TYPE`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE TABLE IF NOT EXISTS `anidra`.`fc_hospital` (
  `HOSPITAL_KEY` VARCHAR(20) NOT NULL,
  `HOSPITAL_ID` VARCHAR(15) NOT NULL,
  `HOSPITAL_NAME` VARCHAR(100) NOT NULL,
  `PHONE_PRIMARY` VARCHAR(14) NOT NULL,
  `EMAIL_ID` VARCHAR(100) NOT NULL,
  `PHONE_SECONDARY` VARCHAR(14) NULL DEFAULT NULL,
  `CREATE_TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFY_TIMESTAMP` DATETIME NOT NULL,
  `CREATE_USERID` VARCHAR(40) NOT NULL,
  `MODIFY_USERID` VARCHAR(40) NOT NULL,
  `CREATE_APPID` VARCHAR(40) NULL DEFAULT NULL,
  `MODIFY_APPID` VARCHAR(40) NULL DEFAULT NULL,
  `COMMENTS` VARCHAR(1000) NULL DEFAULT NULL,
  `REGISTERED_ID` VARCHAR(40) NULL DEFAULT NULL,
  `REGISTERED_ID_TYPE` VARCHAR(20) NULL DEFAULT NULL,
  `REGISTERED_ID_COUNTRY` VARCHAR(20) NULL DEFAULT NULL,
  `TIME_ZONE` VARCHAR(100) NULL DEFAULT NULL,
  `ADDRESS_LINE_1` VARCHAR(70) NOT NULL,
  `ADDRESS_LINE_2` VARCHAR(70) NULL DEFAULT NULL,
  `ADDRESS_LINE_3` VARCHAR(70) NULL DEFAULT NULL,
  `ADDRESS_LINE_4` VARCHAR(70) NULL DEFAULT NULL,
  `CITY` VARCHAR(35) NOT NULL,
  `STATE` VARCHAR(35) NOT NULL,
  `ZIP_CODE` VARCHAR(6) NULL DEFAULT NULL,
  `COUNTRY` VARCHAR(40) NOT NULL,
  `STATUS` VARCHAR(1) NULL DEFAULT 'Y',
  PRIMARY KEY (`HOSPITAL_KEY`),
  INDEX `HOSPITAL_ID` (`HOSPITAL_ID` ASC) VISIBLE,
  INDEX `PHONE_PRIMARY` (`PHONE_PRIMARY` ASC) VISIBLE,
  INDEX `EMAIL_ID` (`EMAIL_ID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE TABLE IF NOT EXISTS `anidra`.`pr_patient` (
  `PATIENT_KEY` VARCHAR(20) NOT NULL,
  `PATIENT_ID` VARCHAR(15) NOT NULL,
  `HOSPITAL_KEY` VARCHAR(20) NOT NULL,
  `TITLE` VARCHAR(15) NOT NULL,
  `FIRST_NAME` VARCHAR(64) NOT NULL,
  `MIDDLE_NAME` VARCHAR(40) NULL DEFAULT NULL,
  `LAST_NAME` VARCHAR(64) NOT NULL,
  `SUFFIX` VARCHAR(40) NULL DEFAULT NULL,
  `DOB` DATE NOT NULL,
  `SEX` CHAR(1) NOT NULL,
  `ISD_PRIMARY` VARCHAR(10) NULL DEFAULT NULL,
  `PHONE_PRIMARY` VARCHAR(14) NULL DEFAULT NULL,
  `EMAIL_ID` VARCHAR(100) NULL DEFAULT NULL,
  `PHONE_SECONDARY` VARCHAR(14) NULL DEFAULT NULL,
  `CREATE_TIMESTAMP` TIMESTAMP NULL DEFAULT NULL,
  `MODIFY_TIMESTAMP` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CREATE_USERID` VARCHAR(40) NOT NULL,
  `MODIFY_USERID` VARCHAR(40) NOT NULL,
  `CREATE_APPID` VARCHAR(40) NULL DEFAULT NULL,
  `MODIFY_APPID` VARCHAR(40) NULL DEFAULT NULL,
  `COMMENTS` VARCHAR(1000) NULL DEFAULT NULL,
  `PRE_EXISTING_CONDITIONS` VARCHAR(1000) NULL DEFAULT NULL,
  `JOB` VARCHAR(50) NULL DEFAULT NULL,
  `JOB_TITLE` VARCHAR(40) NULL DEFAULT NULL,
  `REGISTERED_ID` VARCHAR(40) NULL DEFAULT NULL,
  `REGISTERED_ID_TYPE` VARCHAR(20) NULL DEFAULT NULL,
  `REGISTERED_ID_CONTRY` VARCHAR(20) NULL DEFAULT NULL,
  `EMERGENCY_CONTACT` VARCHAR(40) NOT NULL,
  `EMERGENCY_PHONE` VARCHAR(15) NOT NULL,
  `EMERGENCY_PHONE_2` VARCHAR(15) NULL DEFAULT NULL,
  `EMERGENCY_RELATIONSHIP` VARCHAR(40) NULL DEFAULT NULL,
  `ALTERNATE_EMAIL_ID` VARCHAR(100) NULL DEFAULT NULL,
  `EMAIL_VERIFICATION_STATUS` CHAR(1) NULL DEFAULT 'N',
  `PRIMARY_PHONE_VER_STATUS` CHAR(1) NULL DEFAULT 'N',
  `SECONDARY_PHONE_VER_STATUS` CHAR(1) NULL DEFAULT 'N',
  `EMERGENCY_PHONE_VER_STATUS` CHAR(1) NULL DEFAULT 'N',
  `TIME_ZONE` VARCHAR(250) NULL DEFAULT NULL,
  `ADDRESS_LINE_1` VARCHAR(70) NULL DEFAULT NULL,
  `ADDRESS_LINE_2` VARCHAR(70) NULL DEFAULT NULL,
  `ADDRESS_LINE_3` VARCHAR(70) NULL DEFAULT NULL,
  `ADDRESS_LINE_4` VARCHAR(70) NULL DEFAULT NULL,
  `CITY` VARCHAR(35) NULL DEFAULT NULL,
  `STATE` VARCHAR(35) NULL DEFAULT NULL,
  `ZIP_CODE` VARCHAR(6) NULL DEFAULT NULL,
  `COUNTRY_RESIDENCE` VARCHAR(40) NULL DEFAULT NULL,
  `USER_KEY` VARCHAR(20) NULL DEFAULT NULL,
  `Status` VARCHAR(1) NOT NULL DEFAULT 'Y',
  `PlanType` VARCHAR(20) NULL DEFAULT NULL,
  `UserType` VARCHAR(20) NULL DEFAULT NULL,
  `Firebase_ID` VARCHAR(20) NULL DEFAULT NULL,
  `Inv_Count` INT NULL DEFAULT NULL,
  PRIMARY KEY (`PATIENT_KEY`),
  UNIQUE INDEX `PATIENT_ID` (`PATIENT_ID` ASC, `HOSPITAL_KEY` ASC) VISIBLE,
  UNIQUE INDEX `USER_KEY` (`USER_KEY` ASC) VISIBLE,
  UNIQUE INDEX `REGISTERED_ID` (`REGISTERED_ID` ASC, `REGISTERED_ID_TYPE` ASC, `REGISTERED_ID_CONTRY` ASC) VISIBLE,
  INDEX `PHONE_PRIMARY` (`PHONE_PRIMARY` ASC) VISIBLE,
  INDEX `EMAIL_ID` (`EMAIL_ID` ASC) VISIBLE,
  INDEX `HOSPITAL_ID` (`HOSPITAL_KEY` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE TABLE IF NOT EXISTS `anidra`.`ecg_resource` (
  `id` BINARY(16) NOT NULL,
  `hospital_key` VARCHAR(20) NOT NULL,
  `patient_key` VARCHAR(20) NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `type` VARCHAR(255) NULL DEFAULT NULL,
  `frequency` INT NULL DEFAULT NULL,
  `noise` FLOAT NULL DEFAULT NULL,
  `overlap` FLOAT NULL DEFAULT NULL,
  `total_signals` INT NULL DEFAULT NULL,
  `total_windows` INT NULL DEFAULT NULL,
  `total_detects` INT NULL DEFAULT NULL,
  `start_time` DATETIME NULL DEFAULT NULL,
  `end_time` DATETIME NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_hospital_key` (`hospital_key` ASC) VISIBLE,
  INDEX `fk_patient_key` (`patient_key` ASC) VISIBLE,
  CONSTRAINT `fk_hospital_key`
    FOREIGN KEY (`hospital_key`)
    REFERENCES `anidra`.`fc_hospital` (`HOSPITAL_KEY`),
  CONSTRAINT `fk_patient_key`
    FOREIGN KEY (`patient_key`)
    REFERENCES `anidra`.`pr_patient` (`PATIENT_KEY`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE TABLE IF NOT EXISTS `anidra`.`ecg_window` (
  `id` BINARY(16) NOT NULL,
  `resource_id` BINARY(16) NULL DEFAULT NULL,
  `position` INT NOT NULL,
  `start_signal` INT NULL DEFAULT NULL,
  `end_signal` INT NULL DEFAULT NULL,
  `rr_sum` FLOAT NULL DEFAULT NULL,
  `rr_range` FLOAT NULL DEFAULT NULL,
  `rr_avg` FLOAT NULL DEFAULT NULL,
  `rr_median` FLOAT NULL DEFAULT NULL,
  `rr_iqr` FLOAT NULL DEFAULT NULL,
  `rr_std` FLOAT NULL DEFAULT NULL,
  `detected` TINYINT(1) NULL DEFAULT NULL,
  `pre_detected` TINYINT(1) NULL DEFAULT NULL,
  `post_detected` TINYINT(1) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `_resource_position_uc` (`resource_id` ASC, `position` ASC) VISIBLE,
  INDEX `ix_ecg_window_resource_id` (`resource_id` ASC) VISIBLE,
  CONSTRAINT `ecg_window_ibfk_1`
    FOREIGN KEY (`resource_id`)
    REFERENCES `anidra`.`ecg_resource` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


CREATE TABLE IF NOT EXISTS `anidra`.`ecg_signal` (
  `id` BINARY(16) NOT NULL,
  `window_id` BINARY(16) NULL DEFAULT NULL,
  `position` INT NOT NULL,
  `value` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `_window_position_uc` (`window_id` ASC, `position` ASC) VISIBLE,
  INDEX `ix_ecg_signal_window_id` (`window_id` ASC) VISIBLE,
  CONSTRAINT `ecg_signal_ibfk_1`
    FOREIGN KEY (`window_id`)
    REFERENCES `anidra`.`ecg_window` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


CREATE TABLE IF NOT EXISTS `anidra`.`mail` (
  `mail_id` VARCHAR(21) NOT NULL,
  `subject` VARCHAR(250) NOT NULL,
  `mail_From` VARCHAR(20) NOT NULL,
  `mail_to` VARCHAR(20) NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`mail_id`),
  INDEX `mail_From` (`mail_From` ASC) VISIBLE,
  INDEX `mail_to` (`mail_to` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


CREATE TABLE IF NOT EXISTS `anidra`.`message` (
  `msg_id` VARCHAR(20) NOT NULL,
  `content` VARCHAR(500) NOT NULL,
  `has_read` TINYINT(1) NOT NULL DEFAULT '0',
  `create_timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `mail_id` VARCHAR(21) NOT NULL,
  PRIMARY KEY (`msg_id`),
  INDEX `mail_id` (`mail_id` ASC) VISIBLE,
  CONSTRAINT `message_ibfk_1`
    FOREIGN KEY (`mail_id`)
    REFERENCES `anidra`.`mail` (`mail_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE TABLE IF NOT EXISTS `anidra`.`patient_doctor_map` (
  `Inv_Key` VARCHAR(20) NOT NULL,
  `D_Key` VARCHAR(20) NULL DEFAULT NULL,
  `P_Key` VARCHAR(20) NULL DEFAULT NULL,
  `Map_Status` VARCHAR(20) NULL DEFAULT NULL,
  `Notif_Status` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`Inv_Key`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


CREATE TABLE IF NOT EXISTS `anidra`.`patient_mews_config` (
  `config_id` INT NOT NULL AUTO_INCREMENT,
  `spo2_min` INT NOT NULL DEFAULT '92',
  `spo2_max` INT NOT NULL DEFAULT '100',
  `pr_min` INT NOT NULL DEFAULT '50',
  `pr_max` INT NOT NULL DEFAULT '99',
  `resp_min` INT NOT NULL DEFAULT '9',
  `resp_max` INT NOT NULL DEFAULT '20',
  `temp_min` INT NOT NULL DEFAULT '97',
  `temp_max` INT NOT NULL DEFAULT '101',
  `sys_min` INT NOT NULL DEFAULT '90',
  `sys_max` INT NOT NULL DEFAULT '120',
  `dia_min` INT NOT NULL DEFAULT '0',
  `dia_max` INT NOT NULL DEFAULT '0',
  `patient_key` VARCHAR(22) NOT NULL,
  PRIMARY KEY (`config_id`),
  UNIQUE INDEX `patient` (`patient_key` ASC) VISIBLE,
  CONSTRAINT `patient_mews_config_ibfk_1`
    FOREIGN KEY (`patient_key`)
    REFERENCES `anidra`.`pr_patient` (`PATIENT_KEY`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE TABLE IF NOT EXISTS `anidra`.`pm_alert_config` (
  `PATIENT_KEY` VARCHAR(20) NOT NULL,
  `FIRST_ALERT_DOCTOR` VARCHAR(20) NULL DEFAULT NULL,
  `FIRST_ALERT_NURSE` VARCHAR(20) NULL DEFAULT NULL,
  `ESCALATION_ALERT_DOCTOR` VARCHAR(20) NULL DEFAULT NULL,
  `ESCALATION_ALERT_NURSE` VARCHAR(20) NULL DEFAULT NULL,
  `SECOND_ESCALATION_ALERT_DOCTOR` VARCHAR(20) NULL DEFAULT NULL,
  `SECOND_ESCALATION_ALERT_NURSE` VARCHAR(20) NULL DEFAULT NULL,
  `FIRST_NUMBER` VARCHAR(20) NULL DEFAULT NULL,
  `SECOND_NUMBER` VARCHAR(20) NULL DEFAULT NULL,
  `DOCTOR_NUMBER` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`PATIENT_KEY`),
  INDEX `FIRST_ALERT_DOCTOR` (`FIRST_ALERT_DOCTOR` ASC) VISIBLE,
  INDEX `FIRST_ALERT_NURSE` (`FIRST_ALERT_NURSE` ASC) VISIBLE,
  INDEX `ESCALATION_ALERT_DOCTOR` (`ESCALATION_ALERT_DOCTOR` ASC) VISIBLE,
  INDEX `ESCALATION_ALERT_NURSE` (`ESCALATION_ALERT_NURSE` ASC) VISIBLE,
  INDEX `SECOND_ESCALATION_ALERT_DOCTOR` (`SECOND_ESCALATION_ALERT_DOCTOR` ASC) VISIBLE,
  INDEX `SECOND_ESCALATION_ALERT_NURSE` (`SECOND_ESCALATION_ALERT_NURSE` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE TABLE IF NOT EXISTS `anidra`.`pm_sensor_allocation` (
  `SENSOR_ALLOC_ID` VARCHAR(20) NOT NULL,
  `SENSOR_ID` VARCHAR(20) NOT NULL,
  `ADMISSION_KEY` VARCHAR(20) NOT NULL,
  `EFFECTIVE_FROM` DATETIME NOT NULL,
  `EFFECTIVE_TO` DATETIME NULL DEFAULT NULL,
  `CREATE_TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFY_TIMESTAMP` DATETIME NULL DEFAULT NULL,
  `CREATE_USERID` VARCHAR(40) NOT NULL,
  `MODIFY_USERID` VARCHAR(40) NOT NULL,
  `CREATED_APPID` VARCHAR(40) NULL DEFAULT NULL,
  `MODIFY_APPID` VARCHAR(40) NULL DEFAULT NULL,
  `alerts_status` VARCHAR(1) NOT NULL DEFAULT 'Y',
  PRIMARY KEY (`SENSOR_ALLOC_ID`),
  UNIQUE INDEX `SENSOR_ID_2` (`SENSOR_ID` ASC, `ADMISSION_KEY` ASC, `EFFECTIVE_FROM` ASC, `EFFECTIVE_TO` ASC) VISIBLE,
  INDEX `SENSOR_ID` (`SENSOR_ID` ASC) VISIBLE,
  INDEX `ADMISSION_KEY` (`ADMISSION_KEY` ASC) VISIBLE,
  CONSTRAINT `pm_sensor_allocation_ibfk_1`
    FOREIGN KEY (`SENSOR_ID`)
    REFERENCES `anidra`.`sensor` (`sensor_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE TABLE IF NOT EXISTS `anidra`.`pm_ecg_score` (
  `id` BINARY(16) NOT NULL,
  `sensor_id` VARCHAR(20) NOT NULL,
  `sensor_alloc_id` VARCHAR(20) NOT NULL,
  `ecg_score` TINYINT(1) NOT NULL,
  `create_timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `sensor_alloc_id_index` (`sensor_alloc_id` ASC) VISIBLE,
  INDEX `sensor_id_index` (`sensor_id` ASC) VISIBLE,
  CONSTRAINT `pm_ecg_score_ibfk_1`
    FOREIGN KEY (`sensor_alloc_id`)
    REFERENCES `anidra`.`pm_sensor_allocation` (`SENSOR_ALLOC_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


CREATE TABLE IF NOT EXISTS `anidra`.`pm_mews_score` (
  `MEWS_KEY` VARCHAR(20) NOT NULL,
  `SENSOR_ID` VARCHAR(20) NOT NULL,
  `SENSOR_ALLOC_ID` VARCHAR(20) NOT NULL,
  `MEWS_SCORE` DECIMAL(3,1) NOT NULL,
  `model_df_score` DECIMAL(3,2) NULL DEFAULT NULL,
  `model_nn_score` DECIMAL(3,2) NULL DEFAULT NULL,
  `model_th_score` DECIMAL(3,2) NULL DEFAULT NULL,
  `consensus_score` DECIMAL(3,1) NULL DEFAULT NULL,
  `alarm_reason` VARCHAR(256) NULL DEFAULT NULL,
  `spo2` INT NOT NULL,
  `resp` INT NOT NULL,
  `pr` INT NOT NULL,
  `temp` INT NOT NULL,
  `bp` INT NOT NULL,
  `SPO2_VAL` DECIMAL(10,0) NULL DEFAULT NULL,
  `PR_VAL` DECIMAL(10,0) NULL DEFAULT NULL,
  `temp_val` DECIMAL(10,1) NULL DEFAULT NULL,
  `RESP_VAL` DECIMAL(10,0) NULL DEFAULT NULL,
  `SYS_VAL` DECIMAL(10,0) NULL DEFAULT NULL,
  `DIA_VAL` DECIMAL(10,0) NULL DEFAULT NULL,
  `CREATE_TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATE_APPID` VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (`MEWS_KEY`),
  INDEX `SENSOR_ALLOC_ID` (`SENSOR_ALLOC_ID` ASC) VISIBLE,
  INDEX `SENSOR_ID` (`SENSOR_ID` ASC) VISIBLE,
  CONSTRAINT `pm_mews_score_ibfk_1`
    FOREIGN KEY (`SENSOR_ALLOC_ID`)
    REFERENCES `anidra`.`pm_sensor_allocation` (`SENSOR_ALLOC_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE TABLE IF NOT EXISTS `anidra`.`pm_sensor_data` (
  `SENSOR_DATA_KEY` VARCHAR(20) NOT NULL,
  `SENSOR_ALLOC_ID` VARCHAR(20) NOT NULL,
  `SENSOR_ID` VARCHAR(20) NOT NULL,
  `SPO2` DECIMAL(3,0) NOT NULL,
  `RESP_RATE` DECIMAL(3,0) NOT NULL,
  `PULSE_RATE` DECIMAL(3,0) NOT NULL,
  `TEMPERATURE` DECIMAL(3,1) NOT NULL,
  `DIA_PRESSURE` DECIMAL(3,0) NOT NULL,
  `SYS_PRESSURE` DECIMAL(3,0) NOT NULL,
  `CREATE_TIMESTAMP` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`SENSOR_DATA_KEY`),
  INDEX `SENSOR_ID` (`SENSOR_ID` ASC) VISIBLE,
  INDEX `SENSOR_ALLOC_ID` (`SENSOR_ALLOC_ID` ASC) VISIBLE,
  INDEX `SENSOR_ID_2` USING BTREE (`SENSOR_ID`, `CREATE_TIMESTAMP`) VISIBLE,
  CONSTRAINT `fk_sensor`
    FOREIGN KEY (`SENSOR_ID`)
    REFERENCES `anidra`.`sensor` (`sensor_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `pm_sensor_data_ibfk_1`
    FOREIGN KEY (`SENSOR_ALLOC_ID`)
    REFERENCES `anidra`.`pm_sensor_allocation` (`SENSOR_ALLOC_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE TABLE IF NOT EXISTS `anidra`.`pr_doctor` (
  `DOCTOR_KEY` VARCHAR(20) NOT NULL,
  `DOCTOR_ID` VARCHAR(15) NULL DEFAULT NULL,
  `HOSPITAL_KEY` VARCHAR(20) NULL DEFAULT NULL,
  `TITLE` VARCHAR(15) NOT NULL,
  `FIRST_NAME` VARCHAR(64) NOT NULL,
  `MIDDLE_NAME` VARCHAR(40) NULL DEFAULT NULL,
  `LAST_NAME` VARCHAR(64) NOT NULL,
  `SUFFIX` VARCHAR(40) NULL DEFAULT NULL,
  `DOB` DATE NULL DEFAULT NULL,
  `SEX` CHAR(1) NULL DEFAULT NULL,
  `PHONE_PRIMARY` VARCHAR(14) NOT NULL,
  `EMAIL_ID` VARCHAR(100) NOT NULL,
  `PHONE_SECONDARY` VARCHAR(14) NULL DEFAULT NULL,
  `SNOOZE` TINYINT(1) NULL DEFAULT NULL,
  `PREFERRED_ALERT_TYPE` VARCHAR(4) NULL DEFAULT NULL,
  `OOO_START_DATE` DATETIME NULL DEFAULT NULL,
  `OOO_END_DATE` DATETIME NULL DEFAULT NULL,
  `CREATE_TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `MODIFY_TIMESTAMP` DATETIME NOT NULL,
  `CREATE_USERID` VARCHAR(40) NOT NULL,
  `MODIFY_USERID` VARCHAR(40) NOT NULL,
  `CREATE_APPID` VARCHAR(40) NULL DEFAULT NULL,
  `MODIFY_APPID` VARCHAR(40) NULL DEFAULT NULL,
  `COMMENTS` VARCHAR(1000) NULL DEFAULT NULL,
  `DISCIPLINE` VARCHAR(50) NULL DEFAULT NULL,
  `JOB_TITLE` VARCHAR(40) NULL DEFAULT NULL,
  `REGISTERED_ID` VARCHAR(40) NULL DEFAULT NULL,
  `REGISTERED_ID_TYPE` VARCHAR(20) NULL DEFAULT NULL,
  `REGISTERED_ID_COUNTRY` VARCHAR(20) NULL DEFAULT NULL,
  `ALTERNATE_EMAIL_ID` VARCHAR(100) NULL DEFAULT NULL,
  `EMAIL_VERIFICATION_STATUS` CHAR(1) NULL DEFAULT NULL,
  `PRIMARY_PHONE_VER_STATUS` CHAR(1) NULL DEFAULT NULL,
  `SECONDARY_PHONE_VER_STATUS` CHAR(1) NULL DEFAULT NULL,
  `EMERGENCY_PHONE_VER_STATUS` CHAR(1) NULL DEFAULT NULL,
  `TIME_ZONE` VARCHAR(250) NULL DEFAULT NULL,
  `ADDRESS_LINE_1` VARCHAR(70) NULL DEFAULT NULL,
  `ADDRESS_LINE_2` VARCHAR(70) NULL DEFAULT NULL,
  `ADDRESS_LINE_3` VARCHAR(70) NULL DEFAULT NULL,
  `ADDRESS_LINE_4` VARCHAR(70) NULL DEFAULT NULL,
  `CITY` VARCHAR(35) NULL DEFAULT NULL,
  `STATE` VARCHAR(35) NULL DEFAULT NULL,
  `ZIP_CODE` VARCHAR(6) NULL DEFAULT NULL,
  `COUNTRY_RESIDENCE` VARCHAR(40) NULL DEFAULT NULL,
  `USER_KEY` VARCHAR(20) NOT NULL,
  `Status` VARCHAR(1) NOT NULL DEFAULT 'Y',
  `Firebase_ID` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`DOCTOR_KEY`),
  UNIQUE INDEX `USER_KEY` (`USER_KEY` ASC) VISIBLE,
  INDEX `PHONE_PRIMARY` (`PHONE_PRIMARY` ASC) VISIBLE,
  INDEX `EMAIL_ID` (`EMAIL_ID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE TABLE IF NOT EXISTS `anidra`.`pr_nurse` (
  `NURSE_KEY` VARCHAR(20) NOT NULL,
  `NURSE_ID` VARCHAR(15) NOT NULL,
  `HOSPITAL_KEY` VARCHAR(20) NOT NULL,
  `TITLE` VARCHAR(15) NOT NULL,
  `FIRST_NAME` VARCHAR(64) NOT NULL,
  `MIDDLE_NAME` VARCHAR(40) NULL DEFAULT NULL,
  `LAST_NAME` VARCHAR(64) NOT NULL,
  `SUFFIX` VARCHAR(40) NULL DEFAULT NULL,
  `DOB` DATE NULL DEFAULT NULL,
  `SEX` CHAR(1) NULL DEFAULT NULL,
  `PHONE_PRIMARY` VARCHAR(20) NOT NULL,
  `EMAIL_ID` VARCHAR(100) NOT NULL,
  `PHONE_SECONDARY` VARCHAR(20) NULL DEFAULT NULL,
  `SNOOZE` TINYINT(1) NULL DEFAULT NULL,
  `PREFERRED_ALERT_TYPE` VARCHAR(5) NULL DEFAULT NULL,
  `OOO_START_DATE` DATETIME NULL DEFAULT NULL,
  `OOO_END_DATE` DATETIME NULL DEFAULT NULL,
  `CREATE_TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `MODIFY_TIMESTAMP` DATETIME NOT NULL,
  `CREATE_USERID` VARCHAR(40) NOT NULL,
  `MODIFY_USERID` VARCHAR(40) NOT NULL,
  `CREATE_APPID` VARCHAR(40) NULL DEFAULT NULL,
  `MODIFY_APPID` VARCHAR(40) NULL DEFAULT NULL,
  `COMMENTS` VARCHAR(1000) NULL DEFAULT NULL,
  `DISCIPLINE` VARCHAR(50) NULL DEFAULT NULL,
  `JOB_TITLE` VARCHAR(40) NULL DEFAULT NULL,
  `REGISTERED_ID` VARCHAR(40) NULL DEFAULT NULL,
  `REGISTERED_ID_TYPE` VARCHAR(20) NULL DEFAULT NULL,
  `REGISTERED_ID_COUNTRY` VARCHAR(20) NULL DEFAULT NULL,
  `ALTERNATE_EMAIL_ID` VARCHAR(100) NULL DEFAULT NULL,
  `EMAIL_VERIFICATION_STATUS` CHAR(1) NULL DEFAULT NULL,
  `PRIMARY_PHONE_VER_STATUS` CHAR(1) NULL DEFAULT NULL,
  `SECONDARY_PHONE_VER_STATUS` CHAR(1) NULL DEFAULT NULL,
  `EMERGENCY_PHONE_VER_STATUS` CHAR(1) NULL DEFAULT NULL,
  `TIME_ZONE` VARCHAR(250) NULL DEFAULT NULL,
  `ADDRESS_LINE_1` VARCHAR(70) NULL DEFAULT NULL,
  `ADDRESS_LINE_2` VARCHAR(70) NULL DEFAULT NULL,
  `ADDRESS_LINE_3` VARCHAR(70) NULL DEFAULT NULL,
  `ADDRESS_LINE_4` VARCHAR(70) NULL DEFAULT NULL,
  `CITY` VARCHAR(35) NULL DEFAULT NULL,
  `STATE` VARCHAR(35) NULL DEFAULT NULL,
  `ZIP_CODE` VARCHAR(6) NULL DEFAULT NULL,
  `COUNTRY_RESIDENCE` VARCHAR(40) NULL DEFAULT NULL,
  `USER_KEY` VARCHAR(20) NOT NULL,
  `Status` VARCHAR(1) NULL DEFAULT 'Y',
  PRIMARY KEY (`NURSE_KEY`),
  UNIQUE INDEX `USER_KEY` (`USER_KEY` ASC) VISIBLE,
  UNIQUE INDEX `NURSE_ID` (`NURSE_ID` ASC, `HOSPITAL_KEY` ASC) VISIBLE,
  INDEX `PHONE_PRIMARY` (`PHONE_PRIMARY` ASC) VISIBLE,
  INDEX `EMAIL_ID` (`EMAIL_ID` ASC) VISIBLE,
  INDEX `HOSPITAL_KEY` (`HOSPITAL_KEY` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


CREATE TABLE IF NOT EXISTS `anidra`.`pr_patient_admission` (
  `ADMISSION_KEY` VARCHAR(20) NOT NULL,
  `PATIENT_KEY` VARCHAR(20) NOT NULL,
  `HOSPITAL_KEY` VARCHAR(20) NOT NULL,
  `BED` VARCHAR(40) NULL DEFAULT NULL,
  `WARD` VARCHAR(40) NULL DEFAULT NULL,
  `DOA` DATE NOT NULL,
  `DOD` DATE NULL DEFAULT NULL,
  `DOCTOR_ICHARGE_DAY` VARCHAR(20) NULL DEFAULT NULL,
  `NURSE_ICHARGE_DAY` VARCHAR(20) NULL DEFAULT NULL,
  `DOCTOR_ICHARGE_NIGHT` VARCHAR(20) NULL DEFAULT NULL,
  `NURSE_ICHARGE_NIGHT` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`ADMISSION_KEY`),
  INDEX `PATIENT_KEY` (`PATIENT_KEY` ASC) VISIBLE,
  INDEX `DOCTOR_ICHARGE_DAY` (`DOCTOR_ICHARGE_DAY` ASC) VISIBLE,
  INDEX `NURSE_ICHARGE_DAY` (`NURSE_ICHARGE_DAY` ASC) VISIBLE,
  INDEX `DOCTOR_ICHARGE_NIGHT` (`DOCTOR_ICHARGE_NIGHT` ASC) VISIBLE,
  INDEX `NURSE_ICHARGE_NIGHT` (`NURSE_ICHARGE_NIGHT` ASC) VISIBLE,
  INDEX `HOSPITAL_ID` USING BTREE (`HOSPITAL_KEY`) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE TABLE IF NOT EXISTS `anidra`.`pr_patient_threshold` (
  `PATIENT_THRESHOLD_KEY` INT NOT NULL AUTO_INCREMENT,
  `PATIENT_KEY` VARCHAR(20) NOT NULL,
  `HOSPITAL_KEY` VARCHAR(20) NULL DEFAULT NULL,
  `SPO2_MAX` DECIMAL(3,0) NOT NULL,
  `SPO2_MIN` DECIMAL(3,0) NOT NULL,
  `RESP_RATE_MAX` DECIMAL(3,0) NOT NULL,
  `RESP_RATE_MIN` DECIMAL(3,0) NOT NULL,
  `PULSE_RATE_MAX` DECIMAL(3,0) NOT NULL,
  `PULSE_RATE_MIN` DECIMAL(3,0) NOT NULL,
  `TEMPERATURE_MAX` DECIMAL(3,1) NOT NULL,
  `TEMPERATURE_MIN` DECIMAL(3,1) NOT NULL,
  `SYS_PRESSURE_MAX` DECIMAL(3,0) NOT NULL,
  `SYS_PRESSURE_MIN` DECIMAL(3,0) NOT NULL,
  `DIA_PRESSURE_MAX` DECIMAL(3,0) NOT NULL,
  `DIA_PRESSURE_MIN` DECIMAL(3,0) NOT NULL,
  `CREATE_TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFY_TIMESTAMP` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CREATE_USERID` VARCHAR(40) NULL DEFAULT NULL,
  `MODIFY_USERID` VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (`PATIENT_THRESHOLD_KEY`),
  UNIQUE INDEX `PATIENT_KEY` (`PATIENT_KEY` ASC) VISIBLE,
  CONSTRAINT `pr_patient_threshold_ibfk_1`
    FOREIGN KEY (`PATIENT_KEY`)
    REFERENCES `anidra`.`pr_patient` (`PATIENT_KEY`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 72
DEFAULT CHARACTER SET = latin1;


CREATE TABLE IF NOT EXISTS `anidra`.`sc_user` (
  `USER_KEY` VARCHAR(20) NOT NULL,
  `LOGIN_ID` VARCHAR(100) NOT NULL,
  `PASSWORD` VARCHAR(120) NOT NULL,
  `USER_NAME` VARCHAR(100) NOT NULL,
  `HOSPITAL_KEY` VARCHAR(20) NULL DEFAULT NULL,
  `IMAGE_FILE` VARCHAR(150) NULL DEFAULT 'user.png',
  `USER_TYPE` VARCHAR(15) NOT NULL,
  `COMMENTS` VARCHAR(200) NULL DEFAULT NULL,
  `PWD_LAST_CHANGED_ON` DATETIME NULL DEFAULT NULL,
  `IS_ACTIVE` CHAR(1) NOT NULL DEFAULT 'Y',
  `IS_PASSWORD_ENCRYPTED` CHAR(1) NULL DEFAULT 'Y',
  `LDAP_DETAILS` VARCHAR(100) NULL DEFAULT NULL,
  `DEPARTMENT` VARCHAR(50) NULL DEFAULT NULL,
  `SESSION_TIMEOUT` DECIMAL(10,0) NULL DEFAULT NULL,
  `IS_SUPER_USER` CHAR(1) NOT NULL,
  `PASSWORD_CHANGE_FLAG` CHAR(1) NULL DEFAULT NULL,
  `CREATE_TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `MODIFY_TIMESTAMP` DATETIME NOT NULL,
  `CREATE_USERID` VARCHAR(40) NULL DEFAULT NULL,
  `MODIFY_USERID` VARCHAR(40) NULL DEFAULT NULL,
  `CREATE_APPID` VARCHAR(40) NULL DEFAULT NULL,
  `MODIFY_APPID` VARCHAR(40) NULL DEFAULT NULL,
  `SALT` VARCHAR(50) NULL DEFAULT NULL,
  `MAX_PATIENTS` DECIMAL(2,0) NULL DEFAULT NULL,
  `IS_SUPERVISOR` CHAR(1) NOT NULL DEFAULT 'N',
  `DISPLAY_USER_ID` VARCHAR(150) NOT NULL,
  `HAS_PROFILE` CHAR(1) NOT NULL DEFAULT 'N',
  `pin` VARCHAR(4) NULL DEFAULT NULL,
  `token` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`USER_KEY`),
  UNIQUE INDEX `LOGIN_ID` (`LOGIN_ID` ASC) VISIBLE,
  INDEX `HOSPITAL_KEY` (`HOSPITAL_KEY` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `anidra`.`sc_user_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anidra`.`sc_user_group` (
  `USER_GROUP_KEY` VARCHAR(20) NOT NULL,
  `USER_GROUP_ID` VARCHAR(40) NOT NULL,
  `USER_GROUP_NAME` VARCHAR(50) NOT NULL,
  `USER_GROUP_DESCRIPTION` VARCHAR(255) NOT NULL,
  `HOSPITAL_KEY` VARCHAR(20) NULL DEFAULT NULL,
  `IS_ACTIVE` CHAR(1) NOT NULL DEFAULT 'Y',
  `GROUP_OWNER_ID` VARCHAR(40) NULL DEFAULT NULL,
  `CREATE_TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `MODIFY_TIMESTAMP` DATETIME NOT NULL,
  `CREATE_USERID` VARCHAR(40) NOT NULL,
  `MODIFY_USERID` VARCHAR(40) NOT NULL,
  `CREATE_APPID` VARCHAR(40) NULL DEFAULT NULL,
  `MODIFY_APPID` VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (`USER_GROUP_KEY`),
  UNIQUE INDEX `USER_GROUP_ID` (`USER_GROUP_ID` ASC) VISIBLE,
  INDEX `HOSPITAL_KEY` (`HOSPITAL_KEY` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `anidra`.`sc_user_group_members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anidra`.`sc_user_group_members` (
  `MEMBERSHIP_KEY` VARCHAR(20) NOT NULL,
  `USER_KEY` VARCHAR(20) NOT NULL,
  `USER_GROUP_KEY` VARCHAR(20) NOT NULL,
  `CREATE_TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `MODIFY_TIMESTAMP` DATETIME NOT NULL,
  `CREATE_USERID` VARCHAR(40) NOT NULL,
  `MODIFY_USERID` VARCHAR(40) NOT NULL,
  `CREATE_APPID` VARCHAR(40) NOT NULL,
  `MODIFY_APPID` VARCHAR(40) NOT NULL,
  `IS_PRIMARY` CHAR(1) NOT NULL,
  PRIMARY KEY (`MEMBERSHIP_KEY`),
  INDEX `USER_KEY` (`USER_KEY` ASC) VISIBLE,
  INDEX `USER_GROUP_KEY` (`USER_GROUP_KEY` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `anidra`.`sms_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anidra`.`sms_log` (
  `sms_id` VARCHAR(36) NOT NULL,
  `patient_key` VARCHAR(20) NOT NULL,
  `hospital_key` VARCHAR(20) NOT NULL,
  `message` VARCHAR(150) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `user_key` VARCHAR(22) NOT NULL,
  `create_timestamp` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`sms_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `anidra`.`standalone_kit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anidra`.`standalone_kit` (
  `kit_id` VARCHAR(10) NOT NULL,
  `kit_name` VARCHAR(50) NOT NULL,
  `kit_mac` VARCHAR(20) NOT NULL,
  `comments` VARCHAR(250) NULL DEFAULT '-',
  `downloads` INT NOT NULL DEFAULT '0',
  PRIMARY KEY (`kit_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `anidra`.`temp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anidra`.`temp` (
  `temp_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `anidra`.`template`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anidra`.`template` (
  `template_id` VARCHAR(20) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `type` VARCHAR(30) NOT NULL,
  `content` VARCHAR(512) NOT NULL,
  `platform` VARCHAR(10) NOT NULL,
  `isActive` CHAR(1) NOT NULL DEFAULT 'Y',
  PRIMARY KEY (`template_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `anidra`.`token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anidra`.`token` (
  `user_key` VARCHAR(20) NOT NULL,
  `token` VARCHAR(20) NOT NULL,
  `status` VARCHAR(1) NOT NULL,
  `ip` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`user_key`, `token`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `anidra`.`user_alert_config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anidra`.`user_alert_config` (
  `id` BINARY(16) NOT NULL,
  `user_id` VARCHAR(255) NULL DEFAULT NULL,
  `sms` TINYINT(1) NOT NULL,
  `email` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_id` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `anidra`.`user_complaints`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anidra`.`user_complaints` (
  `REGISTER_COMPLAINT_KEY` VARCHAR(20) NOT NULL,
  `USER_KEY` VARCHAR(20) NOT NULL,
  `NATURE_QUERY` VARCHAR(40) NOT NULL,
  `COMPLAINT_COMMENTS` VARCHAR(120) NOT NULL,
  `CREATE_TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ATTACH_DOCUMENTS` VARCHAR(200) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NULL DEFAULT NULL,
  `Status` CHAR(1) NOT NULL DEFAULT 'O',
  PRIMARY KEY (`REGISTER_COMPLAINT_KEY`),
  INDEX `user_complaints_ibfk_1` (`USER_KEY` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `anidra`.`version`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anidra`.`version` (
  `type` VARCHAR(5) NOT NULL,
  `code` VARCHAR(10) NOT NULL,
  `build` INT NOT NULL,
  `note` VARCHAR(256) NULL DEFAULT NULL,
  `url` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`type`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


